### ISSUE TITLE
First iteration feedback

### ISSUE THREAD

**Issue by Cristiksp** [ec429/SPEngine#1]
Good idea to use already created engines, stick to it, at least for the moment.

Short term:
UI side - have minimum and maximum possible values shown for thrust and ignitions
            - full tooling info - add cost after tooling, untooled cost and cost of tooling are already there
            - no click-through if possible
            - for the moment on the VAB left pane there are details of original engine, might be confusing
            - if it's possible, use the SPEngine UI to mark what configs should be seen in the SPEngine config 
               window, for decluttering purposes
            - what is [U][P] in the SPEngine config window?
            - both sea level thrust and vacuum should be shown

Test flight - separate data for every design will be nice, with maybe some 10-20% flight data taken from 
                    the maximum engine config in the same family and tech level
                 - possibility to change  burn time - it should affect cost and development time

Long term:
KSC integratation - A new design will take an amount of time until it's available depending on some variables  (number of ignitions, tech level, burn time, maybe thrust) 
Visual - increase/decrease the engine depending on the thrust level, just an idea, definitely not essential 
          - choose engine model based on what parts are available (FASA, BDB, SSTU)

Bugs:
Setting ignitions to 0 means infinite ignitions.

**Comment by ec429** [comment]
Thanks for your feedback!

UI.  If I can figure out tooltips they'll be useful for a lot of this "squeeze in extra information".
* min and max, can do (max is already shown in the Family window).  Maybe a tt on the thrust input field.
* cost after tooling is shown in the input row at the bottom.  Also, dividing by 1,000 isn't that hard ;) but again a tt on the cost could do it.
* anti click through is technically possible, haven't got around to it yet.
* VAB pane I know about, still investigating why that happens.  Will have to look at my MM cache a bit more.
* decluttering - already planned.  Though I wonder if I should give each config a guid separate from its name, so you can change their names, and reuse names if you hid the old one.
* Ullage and Pressure-fed.  Again, tts could make that clearer.
* SLT I can probably squeeze in somewhere, yeah.

TF: I looked into the possibility of separating designs, but that (or anything else that procedurally creates TF configs) would be a mountain of work and I'm still not sure if it's actually possible with the TF API as it stands.  That sadly rules out burn time as a design parameter too.  Maybe one for the far future (or after I rewrite TF better and stronger in my own image :rofl:).

KCT: if we ever have build times for regular (tank, fairing etc.) tooling in RP-0, I'll try to integrate with / copy that.
Visual scaling: already tried to do that the easy way (setting `part.scaleFactor`) and it didn't work.  Given how much trouble TweakScale causes, and how much _complicated-looking code_ it seems to need to accomplish that, I'm tempted to just not bother.  But if someone comes along later who knows how to do it, I'll happily take PRs :wink:
Engine models: for the short term I'm assuming anyone who wants a different model can just alter the cfgs to use it.  The part cfgs in SPEngine are really simple, just change the `+PART[somePartName]` in the first line.  I don't really want to create configs for every model, otherwise someone who has all of those mods installed will not only have five J-2 parts, they'll have five J-class proc engine parts as well, cluttering up their VAB, which seems antisocial.

Ignitions bug: derp.  Some classes (eg A, K) are supposed to (at least initially) be ground-light only, and on those, ignitions=0 really does mean zero ignitions.  I need to make the others (upper stages) refuse to set ignitions to 0, because a ground-light-only AJ10 is the silliest idea ever.

**Comment by ec429** [comment]
Several of these are now done:
 * Various tooltips to display more info.
 * Decluttering & renaming in the Design list (this involved a save-breaking change, to give each Design a guid to reference it by).
 * Ignitions bug is fixed.
 * VAB pane now shows all-zeroes rather than original engine thrust&mass.  Still shows a huge number for cost, but I know why and have a change planned which will make it show 0 instead.

**Comment by ec429** [comment]
Anti click through now also done (and I'm finally happy with how unconfigured parts behave in the VAB), so I think all the stuff from this issue that's on the roadmap is done; closing.
