### ISSUE TITLE
Think that Engines are quite overpriced for RP1

### ISSUE THREAD

**Issue by Not-a-flying-brick** [ec429/SPEngine#32]
I think they are more expensive by 10 times(the tooling and unlock prices are fine).For example, RL-10 and R-class engines both have the *4 multiplier but R-class first engine is about 2000 fund worth but RO ones only cost about 200.
This is the situation for most engines.
This has made build time and cost of and rocket skyrocketed.

**Comment by ec429** [comment]
Yeah, this has previously been noted (#20) and is due to RP-1's prices having changed significantly since I wrote the original SPE configs.  At some point I'll redo the configs with `referenceThrust` and `referenceCost` fields to recalc from so that it's hopefully easier to keep them up to date with constantly shifting RP-1.

Closing as dup.
