### ISSUE TITLE
W Class Gimbal limitations tend to make the craft uncontrollable. 

### ISSUE THREAD

**Issue by SerinaTsukaya** [ec429/SPEngine#8]
Game doesn't seem to like only one axis gimbal control and if any side forces occur due to any kind of atmospheric drag it starts to tumble uncontrollably without the ability to recover. I have no idea how they solved this in real life.

**Comment by ec429** [comment]
I believe the IRL answer was to use a pair of engines gimballing tangentially to get pitch & roll control, with "bank and yank" guidance; to first order, the idea is that you roll until 'up' points where you want to go, and then pitch to get there.

However, none of the existing steering PIDs (SAS, RTFC, MJ) know how to B&Y, and I'm not 100% sure about the dynamic stability of a naïve implementation.  At some point I'll prototype a model in a test harness and see if I can come up with something that works, but until then, use 3 or more engines; the game seems to cope alright with that as long as you orient them so that at least one provides roll control; either a pitch/roll pair and one in the middle for yaw, or four in a cross (a pitch/roll pair and a yaw/roll pair) works nicely.
